# Generated by Django 4.2.7 on 2023-11-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(blank=True, max_length=60, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=30)),
                ('programaPTS', models.BooleanField(default=False)),
                ('totalPontos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tab_dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDependente', models.CharField(max_length=60)),
                ('parentesco', models.CharField(max_length=60)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tab_fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFornecedor', models.CharField(max_length=60, unique=True)),
                ('endereco', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tab_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdEstoque', models.IntegerField(default=0)),
                ('estoquePadrao', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tab_loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLoja', models.CharField(max_length=60, unique=True)),
                ('endereco', models.CharField(max_length=60)),
                ('seg_sex', models.CharField(blank=True, max_length=60)),
                ('sab', models.CharField(blank=True, max_length=60)),
                ('dom', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tab_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('tamanho', models.CharField(max_length=60)),
                ('mEmpacotamento', models.CharField(blank=True, max_length=60)),
                ('codBarras', models.IntegerField(unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('fornecedores', models.ManyToManyField(related_name='fornece', to='lojasvarejistasapp.tab_fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='tab_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipoVenda', models.CharField(choices=[('V', 'Virtual'), ('F', 'Fisico')], max_length=1, null=True)),
                ('totalPedido', models.FloatField(default=0.0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_cliente')),
                ('dependente', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_dependente')),
            ],
        ),
        migrations.CreateModel(
            name='tab_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('subTotal', models.FloatField(default=0.0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_inventario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_pedido')),
            ],
        ),
        migrations.AddField(
            model_name='tab_inventario',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_loja'),
        ),
        migrations.AddField(
            model_name='tab_inventario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_produto'),
        ),
    ]
