# Generated by Django 4.2.7 on 2023-11-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=30)),
                ('pontos', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tab_dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDependente', models.CharField(max_length=60)),
                ('parentesco', models.CharField(max_length=60)),
                ('nomeCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_clientes')),
            ],
        ),
    ]
