# Generated by Django 4.2.7 on 2023-11-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=30)),
                ('pontos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tab_dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDependente', models.CharField(max_length=60)),
                ('parentesco', models.CharField(max_length=60)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tab_fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFornecedor', models.CharField(max_length=60, unique=True)),
                ('endereco', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tab_loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLoja', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=60)),
                ('seg_sex', models.CharField(max_length=60)),
                ('sab', models.CharField(max_length=60)),
                ('dom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tab_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('tamanho', models.CharField(max_length=60)),
                ('mEmpacotamento', models.CharField(blank=True, max_length=60)),
                ('codBarras', models.IntegerField(unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('fornecedores', models.ManyToManyField(to='lojasvarejistasapp.tab_fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='tab_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_venda', models.CharField(choices=[('V', 'Virtual'), ('F', 'Fisico')], max_length=1, null=True)),
                ('total_pedido', models.FloatField(default=0.0)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_cliente')),
                ('Dependente', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_dependente')),
            ],
        ),
        migrations.CreateModel(
            name='tab_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('PrecoUnitario', models.FloatField(default=0.0)),
                ('subTotal', models.FloatField(default=0.0)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_pedido')),
            ],
        ),
    ]
