# Generated by Django 4.2.7 on 2023-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojasvarejistasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tab_cliente',
            name='nomeCliente',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
