# Generated by Django 4.2.7 on 2023-11-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojasvarejistasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tab_clientes',
            new_name='tab_cliente',
        ),
    ]
