# Generated by Django 4.2.7 on 2023-11-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojasvarejistasapp', '0002_rename_tab_clientes_tab_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_cliente',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
