# Generated by Django 4.2.7 on 2023-11-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojasvarejistasapp', '0002_alter_tab_cliente_cpf_alter_tab_cliente_nomecliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_item',
            name='precoUnitario',
        ),
        migrations.AlterField(
            model_name='tab_item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_inventario'),
        ),
        migrations.AlterField(
            model_name='tab_pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojasvarejistasapp.tab_cliente'),
        ),
    ]
